export const CATEGORIES_DONE = 'CATEGORIES_DONE';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';
export const GET_CURRENCY_DONE = 'GET_CURRENCY_DONE';
export const GET_CURRENCY_LOADING = 'GET_CURRENCY_LOADING';
export const GET_CURRENCY_ERROR = 'GET_CURRENCY_ERROR';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
